#!/usr/bin/env bash
# =============================================================================
# 01-check-project-deps.sh - Install project dependencies
# Versions are kept strictly aligned with docker-compose.yml:
#   GHC 9.14.1 / PostgreSQL 14.15 / Node.js 26.7.0 / Stack 3.7.1
#
# Installation strategy:
#   - Download prebuilt binaries for GHC / Stack / Node.js from the official sites
#   - Build PostgreSQL / Nginx from source (to avoid hard-coded paths in prebuilt packages)
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/utils.sh"

init_paths
source "${SCRIPT_DIR}/toolchain-authority.sh"

OS="$(detect_os)"
ARCH="$(detect_arch)"
PLATFORM="$(detect_platform)"

STAMP_GHC="${DEPS_DIR}/stamp_ghc_installed"
STAMP_NODE="${DEPS_DIR}/stamp_node_installed"
STAMP_PG="${DEPS_DIR}/stamp_postgres_installed"
STAMP_NGINX="${DEPS_DIR}/stamp_nginx_installed"

# ═════════════════════════════════════════════════════════════════════════════
# 1. GHC 9.14.1 + Stack (docker-compose.yml: GHC_VERSION=9.14.1)
# ═════════════════════════════════════════════════════════════════════════════

generate_ghcup_env() {
    cat > "${GHCUP_DIR}/env" << EOF
# Auto-generated by 01-check-project-deps.sh
export PATH="${GHCUP_DIR}/bin:${GHCUP_DIR}/ghc/${GHC_VERSION}/bin:\$PATH"
EOF
}

install_ghc_and_stack() {
    step "Installing GHC ${GHC_VERSION} + Stack"

    local ghc_info ghc_url ghc_archive ghc_sha256 ghc_identity
    local stk_info stk_url stk_archive stk_sha256 stk_identity
    ghc_info="$(get_ghc_bindist_info)"
    ghc_url="${ghc_info%%|*}"; ghc_archive="${ghc_info##*|}"
    stk_info="$(get_stack_download_info)"
    stk_url="${stk_info%%|*}"; stk_archive="${stk_info##*|}"
    ghc_sha256="$(toolchain_archive_sha256 ghc "$PLATFORM" "$ghc_archive")"
    stk_sha256="$(toolchain_archive_sha256 stack "$PLATFORM" "$stk_archive")"
    ghc_identity="$(ghc_build_identity "$ghc_archive")"
    stk_identity="$(stack_build_identity "$stk_archive")"

    # A stamp is only a convenience marker. Cached tools are never trusted
    # until their lock-bound manifest and raw executable bytes are verified.
    if [ -e "$STAMP_GHC" ] || [ -e "${GHCUP_DIR}/bin/ghc" ] || [ -e "${GHCUP_DIR}/bin/stack" ]; then
        if (verify_ghc_and_stack_installation "$ghc_archive" "$stk_archive"); then
            info "GHC/Stack cache identity verified, skipping installation"
            source_ghcup_env
            touch "$STAMP_GHC"
            return 0
        fi
        warn "GHC/Stack cache identity is missing or invalid; reinstalling from locked archives"
        rm -rf "${GHCUP_DIR}" "$STAMP_GHC"
    fi

    ensure_dir "${GHCUP_DIR}/bin"

    # ── GHC bindist ─────────────────────────────────────────────────────────
    local ghc_path; ghc_path="$(download_cached "$ghc_url" "$ghc_archive" "$ghc_sha256")"

    local extract_dir; extract_dir="$(prepare_extract_dir "ghc")"
    extract_txz "$ghc_path" "$extract_dir" 0 "$ghc_sha256"

    local extracted
    extracted="$(find "$extract_dir" -maxdepth 1 -type d -name 'ghc-*' | head -1)"
    [ -z "$extracted" ] && die "GHC directory not found after extracting the bindist"

    ensure_dir "${GHCUP_DIR}/ghc/${GHC_VERSION}"
    cp -r "${extracted}/"* "${GHCUP_DIR}/ghc/${GHC_VERSION}/"
    install_log "GHC ${GHC_VERSION}" "${GHCUP_DIR}/ghc/${GHC_VERSION}/"

    # Create symlinks under bin/
    local ghc_bin="${GHCUP_DIR}/ghc/${GHC_VERSION}/bin"
    if [ -d "$ghc_bin" ]; then
        for exe in ghc ghci ghc-pkg runghc hp2ps hpc haddock; do
            [ -x "${ghc_bin}/${exe}" ] && ln -sf "../ghc/${GHC_VERSION}/bin/${exe}" "${GHCUP_DIR}/bin/${exe}"
        done
        ln -sf "../ghc/${GHC_VERSION}/bin/ghc" "${GHCUP_DIR}/bin/ghc-${GHC_VERSION}" 2>/dev/null || true
    fi

    cleanup_extract_dir "$extract_dir"

    # ── Stack ───────────────────────────────────────────────────────────────
    local stk_path; stk_path="$(download_cached "$stk_url" "$stk_archive" "$stk_sha256")"

    local stk_extract; stk_extract="$(prepare_extract_dir "stack")"
    extract_tgz "$stk_path" "$stk_extract" 0 "$stk_sha256"
    local stk_bin; stk_bin="$(find "$stk_extract" -type f -name 'stack' -perm -a=x | head -1)"
    [ -z "$stk_bin" ] && die "Stack binary not found"
    cp "$stk_bin" "${GHCUP_DIR}/bin/stack"
    chmod +x "${GHCUP_DIR}/bin/stack"
    install_log "Stack" "${GHCUP_DIR}/bin/stack"
    cleanup_extract_dir "$stk_extract"

    generate_ghcup_env
    write_install_manifest ghc "$GHCUP_DIR" "$ghc_identity" "ghc/${GHC_VERSION}/bin/ghc" \
        "ghc/${GHC_VERSION}/bin/ghc" "bin/ghc" "env"
    write_install_manifest stack "$GHCUP_DIR" "$stk_identity" "bin/stack" "bin/stack"
    verify_ghc_and_stack_installation "$ghc_archive" "$stk_archive"
    source_ghcup_env
    verify_cmd "GHC" "ghc" "--version"
    verify_cmd "Stack" "stack" "--version"
    touch "$STAMP_GHC"
    info "GHC + Stack installation complete"
}

# ═════════════════════════════════════════════════════════════════════════════
# 2. Node.js 26 (prebuilt binary)
# ═════════════════════════════════════════════════════════════════════════════

install_nodejs() {
    step "Installing Node.js"

    # Keep this aligned with mise.toml, the Dockerfile and frontend/package.json
    # `engines`: the locale-catalog generator refuses to run on any other
    # version, because the published catalog revision is bound to it exactly.
    local node_ver="${NODE_VERSION}"

    local node_archive=""
    case "$PLATFORM" in
        macos-arm64)   node_archive="node-v${node_ver}-darwin-arm64.tar.gz" ;;
        macos-x86_64)  node_archive="node-v${node_ver}-darwin-x64.tar.gz" ;;
        linux-x86_64)  node_archive="node-v${node_ver}-linux-x64.tar.gz" ;;
        linux-arm64)   node_archive="node-v${node_ver}-linux-arm64.tar.gz" ;;
        *) die "Unsupported platform: $PLATFORM" ;;
    esac

    local node_url="https://nodejs.org/dist/v${node_ver}/${node_archive}"
    local node_sha256 node_identity
    node_sha256="$(toolchain_archive_sha256 node "$PLATFORM" "$node_archive")"
    node_identity="$(node_binary_identity)"

    if [ -e "$STAMP_NODE" ] || [ -e "${DEPS_DIR}/node/bin/node" ]; then
        if (verify_node_installation); then
            info "Node.js cache identity verified, skipping installation"
            export PATH="${DEPS_DIR}/node/bin:${PATH}"
            touch "$STAMP_NODE"
            return 0
        fi
        warn "Node.js cache identity is missing or invalid; reinstalling from the locked archive"
        rm -rf "${DEPS_DIR}/node" "$STAMP_NODE"
    fi

    local node_path; node_path="$(download_cached "$node_url" "$node_archive" "$node_sha256")"

    rm -rf "${DEPS_DIR}/node"
    ensure_dir "${DEPS_DIR}/node"
    extract_tgz "$node_path" "${DEPS_DIR}/node" 1 "$node_sha256"
    install_log "Node.js ${node_ver}" "${DEPS_DIR}/node/"

    # Ensure the npm command is available
    if [ ! -x "${DEPS_DIR}/node/bin/npm" ] && [ -d "${DEPS_DIR}/node/lib/node_modules/npm/bin" ]; then
        ln -sf "../lib/node_modules/npm/bin/npm-cli.js" "${DEPS_DIR}/node/bin/npm"
        ln -sf "../lib/node_modules/npm/bin/npx-cli.js" "${DEPS_DIR}/node/bin/npx"
    fi

    # The exact executable digest is committed in the lock. Record every
    # Node/npm launcher byte before a cache hit is allowed to execute it.
    write_install_manifest node "${DEPS_DIR}/node" "$node_identity" "bin/node" \
        "bin/node" "bin/npm" "bin/npx" \
        "lib/node_modules/npm/bin/npm-cli.js" "lib/node_modules/npm/bin/npx-cli.js"
    verify_node_installation
    export PATH="${DEPS_DIR}/node/bin:${PATH}"
    verify_cmd "Node.js" "node" "--version"
    verify_cmd "npm" "npm" "--version"
    touch "$STAMP_NODE"
    info "Node.js installation complete"
}

# ═════════════════════════════════════════════════════════════════════════════
# PostgreSQL 14.15 (14.x series, fully data-compatible with the 14.6 runtime in docker-compose.yml)
#   Built from official source on both macOS and Linux — prebuilt binaries
#   embed absolute install paths that don't survive being relocated into the
#   distribution tarball.
#   Build time: about 5-10 minutes depending on the CPU
#   Note: the Haskell package postgresql-libpq-configure requires libpq >= 14.12,
#         so the build version must be >= 14.12 (14.6 would fail to build)
# ═════════════════════════════════════════════════════════════════════════════

install_postgresql() {
    step "Installing PostgreSQL ${PG_VERSION} (build from source)"

    local pg_identity
    pg_identity="$(postgres_build_identity)"
    if [ -e "$STAMP_PG" ] || [ -e "${DEPS_DIR}/postgres/bin/postgres" ]; then
        if (verify_postgres_installation); then
            info "PostgreSQL cache identity verified, skipping installation"
            export PATH="${DEPS_DIR}/postgres/bin:${PATH}"
            touch "$STAMP_PG"
            return 0
        fi
        warn "PostgreSQL cache identity is missing or invalid; rebuilding from the locked source archive"
        rm -rf "${DEPS_DIR}/postgres" "$STAMP_PG"
    fi

    # ── Check build tools ─────────────────────────────────────────────────────
    substep "Checking build tools ..."
    local missing_cc=()
    has_cmd "make"  || missing_cc+=("make")
    if ! has_cmd "cc" && ! has_cmd "gcc"; then
        missing_cc+=("C compiler (gcc/clang)")
    fi
    if [ ${#missing_cc[@]} -gt 0 ]; then
        warn "Missing build tools: ${missing_cc[*]}"
        case "$OS" in
            macos) die "Please run: xcode-select --install" ;;
            linux) die "Please run: sudo apt install -y build-essential" ;;
        esac
    fi
    info "  ✓ Build tools are available"

    # ── Download source tarball (cached under _tmp/) ─────────────────────────
    local pg_archive="${PG_SRC_ARCHIVE}"
    local pg_url="${PG_SRC_URL}"
    local pg_sha256
    pg_sha256="$(toolchain_archive_sha256 postgres "$PLATFORM" "$pg_archive")"
    local pg_path; pg_path="$(download_cached "$pg_url" "$pg_archive" "$pg_sha256")"

    # ── Extract source ───────────────────────────────────────────────────────
    local pg_extract; pg_extract="$(prepare_extract_dir "postgres")"
    extract_tbz "$pg_path" "$pg_extract" 0 "$pg_sha256"
    local pg_src_dir; pg_src_dir="${pg_extract}/postgresql-${PG_VERSION}"
    if [ ! -d "$pg_src_dir" ]; then
        die "PostgreSQL source directory not found: $pg_src_dir"
    fi

    # ── Build and install ─────────────────────────────────────────────────────
    info "Building PostgreSQL ${PG_VERSION} (about 5-10 minutes) ..."
    verify_file_sha256 "$pg_path" "$pg_sha256" "PostgreSQL source before build"
    local cpu_count
    cpu_count="$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)"

    pushd "$pg_src_dir" > /dev/null

	# Select the UUID backend (determines how the uuid-ossp extension is built)
	# --with-uuid is required because setup.sql depends on the uuid-ossp extension
	# The original Docker setup uses the official postgres:14.6-alpine image with contrib included
	#
	# macOS: ships with <uuid/uuid.h> and uuid functions in libSystem
	#   ossp-uuid conflicts with the uuid_t definition in macOS SDK 26+
	#   and cannot be compiled. The e2fs backend uses system interfaces directly with no external dependency.
	#   bsd is also unavailable because macOS lacks uuid_to_string (a FreeBSD function).
	local pg_uuid_flag=""
	case "$OS" in
	    macos)
	        pg_uuid_flag="--with-uuid=e2fs"
	        info "UUID backend: e2fs (built into macOS)"
	        ;;
	    linux)
            # On Linux, prefer e2fs libuuid (apt install uuid-dev)
            # Note: building PostgreSQL requires the development package (uuid-dev), not just the runtime library (libuuid1)
            # Both the header (uuid/uuid.h) and the linker library (libuuid.so, not .so.1) must be present
            local has_uuid_dev=false
            if [ -f /usr/include/uuid/uuid.h ]; then
                # Header exists; now check the linker library (.so symlink, not the .so.1 runtime library)
                if [ -f /usr/lib/x86_64-linux-gnu/libuuid.so ] || \
                   [ -f /usr/lib/aarch64-linux-gnu/libuuid.so ] || \
                   [ -f /usr/lib/libuuid.so ]; then
                    has_uuid_dev=true
                fi
            fi

            if [ "$has_uuid_dev" = true ]; then
                pg_uuid_flag="--with-uuid=e2fs"
                info "UUID backend: e2fs (system uuid-dev)"
            elif has_cmd "apt-get"; then
                warn "The uuid-dev development package is not installed (PostgreSQL build needs headers and linker libraries)"
                warn "Attempting automatic install: sudo apt-get install -y uuid-dev ..."
                sudo apt-get update -qq && sudo apt-get install -y -qq uuid-dev || \
                    die "apt install uuid-dev failed; please run: sudo apt-get install -y uuid-dev"
                pg_uuid_flag="--with-uuid=e2fs"
                info "UUID backend: e2fs (uuid-dev just installed)"
            else
                die "uuid-dev was not found on Linux and apt-get is unavailable. Please install uuid-dev and retry."
            fi
            ;;
    esac

    [ -z "$pg_uuid_flag" ] && die "Unable to determine UUID backend (uuid-ossp is required)"

    substep "./configure --prefix=${DEPS_DIR}/postgres ${pg_uuid_flag} ..."
    # -Wno-error=unguarded-availability-new is only needed for macOS Clang
    # Linux GCC does not support this flag and would fail with "C compiler cannot create executables"
    if [ "$OS" = "macos" ]; then
        export CFLAGS="-Wno-error=unguarded-availability-new"
    else
        export CFLAGS=""
    fi

    if ! ./configure \
            --prefix="${DEPS_DIR}/postgres" \
            --without-readline \
            --without-zlib \
            ${pg_uuid_flag} \
            > "${TMP_DIR}/pg_configure.log" 2>&1; then
        warn "configure failed; see: _tmp/pg_configure.log"
        warn "To inspect the tail: tail -20 offline/_tmp/pg_configure.log"
        die "PostgreSQL configure failed"
    fi

    substep "make -j${cpu_count} ..."
    make -j"${cpu_count}" > "${TMP_DIR}/pg_make.log" 2>&1 \
        || { warn "make failed; see: _tmp/pg_make.log"; die "PostgreSQL make failed"; }

    substep "make install ..."
    make install > "${TMP_DIR}/pg_install.log" 2>&1 \
        || { warn "make install failed; see: _tmp/pg_install.log"; die "PostgreSQL make install failed"; }

    # The uuid-ossp extension lives under contrib and must be built separately
    # setup.sql depends on CREATE EXTENSION "uuid-ossp"
    substep "Building and installing contrib/uuid-ossp ..."
    make -C contrib/uuid-ossp -j"${cpu_count}" > "${TMP_DIR}/pg_uuid_make.log" 2>&1 \
        || { warn "uuid-ossp build failed; see: _tmp/pg_uuid_make.log"; die "contrib/uuid-ossp make failed"; }
    make -C contrib/uuid-ossp install > "${TMP_DIR}/pg_uuid_install.log" 2>&1 \
        || { warn "uuid-ossp install failed; see: _tmp/pg_uuid_install.log"; die "contrib/uuid-ossp make install failed"; }

    popd > /dev/null
    cleanup_extract_dir "$pg_extract"

    install_log "PostgreSQL ${PG_VERSION}" "${DEPS_DIR}/postgres/"

    # ── Verification ────────────────────────────────────────────────────────
    write_install_manifest postgres "${DEPS_DIR}/postgres" "$pg_identity" "bin/postgres" \
        "bin/postgres" "bin/initdb" "bin/pg_ctl" "bin/pg_isready" "bin/psql" "bin/pg_dump" "bin/pg_restore" \
        "bin/pg_config" "bin/createdb"
    verify_postgres_installation
    export PATH="${DEPS_DIR}/postgres/bin:${PATH}"
    verify_cmd "PostgreSQL" "${DEPS_DIR}/postgres/bin/postgres" "--version"
    verify_cmd "initdb"      "${DEPS_DIR}/postgres/bin/initdb"    "--version"
    verify_cmd "pg_ctl"      "${DEPS_DIR}/postgres/bin/pg_ctl"    "--version"
    verify_cmd "pg_dump"     "${DEPS_DIR}/postgres/bin/pg_dump"   "--version"
    verify_cmd "pg_restore"  "${DEPS_DIR}/postgres/bin/pg_restore" "--version"
    substep "pg_config: $(${DEPS_DIR}/postgres/bin/pg_config --version 2>/dev/null)"
    [ -x "${DEPS_DIR}/postgres/bin/createdb" ] && substep "createdb available" || warn "createdb not found"

    touch "$STAMP_PG"
    info "PostgreSQL ${PG_VERSION} installation complete"
}

# ═════════════════════════════════════════════════════════════════════════════
# 4. Nginx — build the exact shipped server from source
#    The project uses Nginx as the frontend server (port 3000) and proxies the API to the backend (3002)
# ═════════════════════════════════════════════════════════════════════════════

install_nginx() {
    step "Installing Nginx ${NGINX_VERSION}"

    local nginx_bin="${DEPS_DIR}/nginx/bin/nginx"
    local ngx_archive="nginx-${NGINX_VERSION}.tar.gz"
    local ngx_url="https://nginx.org/download/${ngx_archive}"
    local ngx_sha256 nginx_identity
    ngx_sha256="$(toolchain_archive_sha256 nginx "$PLATFORM" "$ngx_archive")"
    nginx_identity="$(nginx_build_identity)"

    if [ -e "$STAMP_NGINX" ] || [ -e "$nginx_bin" ]; then
        if (verify_nginx_installation); then
            info "Nginx cache identity and gzip_static capability verified, skipping installation"
            touch "$STAMP_NGINX"
            return 0
        fi
        warn "Nginx cache identity is missing, altered, or lacks gzip_static; rebuilding from the locked source archive"
        rm -rf "${DEPS_DIR}/nginx" "$STAMP_NGINX"
    fi

    # Build from source (minimal build, keep only HTTP core + proxy modules).
    # `gzip_static on` is in the shipped config, so this optional module must
    # be present in the actual binary that is copied into the distribution.
    info "Building nginx from source (about 2-3 minutes) ..."
    local ngx_path; ngx_path="$(download_cached "$ngx_url" "$ngx_archive" "$ngx_sha256")"

    local ngx_extract; ngx_extract="$(prepare_extract_dir "nginx")"
    extract_tgz "$ngx_path" "$ngx_extract" 0 "$ngx_sha256"

    pushd "${ngx_extract}/nginx-${NGINX_VERSION}" > /dev/null

    substep "./configure ..."
    verify_file_sha256 "$ngx_path" "$ngx_sha256" "nginx source before build"
    # -Wno-error=unguarded-availability-new is only needed for macOS Clang
    # Linux GCC does not support this flag and would fail all compiler checks
    if [ "$OS" = "macos" ]; then
        export CFLAGS="-Wno-error=unguarded-availability-new"
    else
        unset CFLAGS 2>/dev/null || true
    fi
    ./configure \
        --prefix="${DEPS_DIR}/nginx" \
        --with-http_gzip_static_module \
        --without-http_gzip_module \
        --without-http_fastcgi_module \
        --without-http_uwsgi_module \
        --without-http_scgi_module \
        --without-http_grpc_module \
        --without-http_memcached_module \
        --without-http_empty_gif_module \
        --without-http_browser_module \
        --without-http_autoindex_module \
        --without-http_geo_module \
        --without-http_split_clients_module \
        --without-http_referer_module \
        --without-http_ssi_module \
        --without-http_userid_module \
        --without-http_mirror_module \
        --without-mail_pop3_module \
        --without-mail_imap_module \
        --without-mail_smtp_module \
        --without-stream_access_module \
        > "${TMP_DIR}/nginx_configure.log" 2>&1 \
        || { warn "configure failed; see: _tmp/nginx_configure.log"; die "Nginx configure failed"; }

    substep "make ..."
    local cpu_count
    cpu_count="$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)"
    make -j"${cpu_count}" > "${TMP_DIR}/nginx_make.log" 2>&1 \
        || { warn "make failed; see: _tmp/nginx_make.log"; die "Nginx make failed"; }

    ensure_dir "$(dirname "$nginx_bin")"
    cp objs/nginx "$nginx_bin"
    chmod +x "$nginx_bin"

    popd > /dev/null
    cleanup_extract_dir "$ngx_extract"

    install_log "Nginx ${NGINX_VERSION}" "$nginx_bin"
    write_install_manifest nginx "${DEPS_DIR}/nginx" "$nginx_identity" "bin/nginx" "bin/nginx"
    verify_nginx_installation
    verify_cmd "Nginx" "$nginx_bin" "-v"
    touch "$STAMP_NGINX"
    info "Nginx installation complete"
}

# ═════════════════════════════════════════════════════════════════════════════
# Main flow
# ═════════════════════════════════════════════════════════════════════════════

main() {
    echo ""
    info "Platform: $PLATFORM"
    info "Dependency dir: $DEPS_DIR"
    info "Download cache: $TMP_DIR"
    echo ""

    ensure_dir "$DEPS_DIR"
    ensure_dir "$TMP_DIR"
    # Do not source a cached ghcup environment or prepend cached executable
    # directories before the install functions have verified their manifests.
    ensure_dir "$STACK_ROOT_DIR"
    export STACK_ROOT="$STACK_ROOT_DIR"

    install_ghc_and_stack
    install_nodejs
    install_postgresql
    install_nginx

    echo ""
    info "All project dependencies are ready"
    echo ""
    echo "  GHC:         $(ghc --version 2>&1 || echo 'N/A')"
    echo "  Stack:       $(stack --version 2>&1 || echo 'N/A')"
    echo "  Node.js:     $(node --version 2>&1 || echo 'N/A')"
    echo "  npm:         $(npm --version 2>&1 || echo 'N/A')"
    echo "  PostgreSQL:  $(${DEPS_DIR}/postgres/bin/postgres --version 2>&1 || echo 'N/A')"
    echo ""
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    main "$@"
fi
