// Loads the exact locale message trees the Vue build produces, plus the
// production helpers the catalog's semantics are derived from.
//
// The catalog must be generated from the same committed snapshot Vue bundles,
// so nothing here re-implements module composition: it runs the project's own
// bundler (Vite, in SSR mode, with the project's `@`/`@homebrew` aliases) over
// `src/locales/messages.ts`'s production `loadLocaleMessages`. Locale `.ts`
// composition, `.json` imports and the `import.meta.glob` homebrew discovery
// therefore behave identically to `npm run build`.

import { createHash } from 'node:crypto'
import { existsSync, readFileSync, readdirSync, rmSync, statSync } from 'node:fs'
import { join, posix, relative as relative_, resolve, sep } from 'node:path'
import { pathToFileURL } from 'node:url'

const VIRTUAL_ENTRY = '\0locale-catalog-entry'

// Source trees whose bytes decide the catalog's content. Every file under
// them is hashed into the catalog revision.
const SOURCE_DIRECTORIES = ['src/locales']

// Per homebrew campaign, only these feed the catalog: the locale messages
// `homebrew.ts` globs in, and the icon map production `replaceIcons` builds
// from. Their campaign directories also hold artwork, which is deliberately
// not walked.
const HOMEBREW_ROOT = 'homebrew'
const HOMEBREW_SOURCES = { directories: ['locales'], files: ['icons.json'] }

// Production modules whose behavior the normalizer mirrors (icon/escape
// classification and the two asset-path variables). A change to any of them
// must produce a new catalog revision even when no locale string changed.
const SEMANTIC_SOURCES = [
  'src/arkham/helpers.ts',
  'src/arkham/homebrewAssets.ts',
  'src/arkham/components/FormattedEntry.vue',
]

function walkFiles(directory) {
  const out = []
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name)
    if (entry.isDirectory()) out.push(...walkFiles(path))
    else if (entry.isFile()) out.push(path)
    else throw new Error(`locale-catalog: refusing to hash non-regular source file ${path}`)
  }
  return out
}

function toPosix(path) {
  return path.split(sep).join(posix.sep)
}

function homebrewSourceFiles(frontendDir) {
  const root = join(frontendDir, HOMEBREW_ROOT)
  const files = []
  for (const campaign of readdirSync(root, { withFileTypes: true })) {
    if (!campaign.isDirectory()) continue
    for (const directory of HOMEBREW_SOURCES.directories) {
      const path = join(root, campaign.name, directory)
      if (existsSync(path)) files.push(...walkFiles(path))
    }
    for (const file of HOMEBREW_SOURCES.files) {
      const path = join(root, campaign.name, file)
      if (existsSync(path)) files.push(path)
    }
  }
  return files
}

/** Every committed file the generated catalog is derived from, path-sorted. */
export function collectSourceFiles(frontendDir) {
  const files = []
  for (const directory of SOURCE_DIRECTORIES) files.push(...walkFiles(join(frontendDir, directory)))
  files.push(...homebrewSourceFiles(frontendDir))
  for (const source of SEMANTIC_SOURCES) files.push(join(frontendDir, source))

  return files
    .map((file) => {
      if (!statSync(file).isFile()) throw new Error(`locale-catalog: ${file} is not a regular file`)
      return {
        path: toPosix(relative_(frontendDir, file)),
        sha256: createHash('sha256').update(readFileSync(file)).digest('hex'),
      }
    })
    .sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0))
}

function readPackageJson(frontendDir, name) {
  const path =
    name === '..'
      ? join(frontendDir, 'package.json')
      : join(frontendDir, 'node_modules', ...name.split('/'), 'package.json')
  if (!existsSync(path)) throw new Error(`locale-catalog: ${name} is not installed (run npm ci)`)
  return JSON.parse(readFileSync(path, 'utf8'))
}

/**
 * The message parser has to be the exact one vue-i18n compiles messages with,
 * otherwise the catalog could interpret a placeholder differently from the web
 * client. This asserts that, fails closed on any mismatch or duplicate
 * install, and returns every version that can influence generated bytes — the
 * bundler that evaluates the locale modules, the vue-i18n stack that defines
 * placeholder and linked-message semantics, and the HTML parser — so upgrading
 * any of them produces a new catalog revision rather than silently changing
 * the bytes behind an immutable URL.
 */
/**
 * The exact Node version the catalog is generated with. A patch release can
 * change JSON escaping, Intl data, or regexp behavior, so the runtime is
 * pinned exactly — in `mise.toml`, `package.json` engines, the Dockerfile, CI
 * and the offline installer — and recorded in the provenance, which makes it
 * part of the revision.
 */
export function nodeRuntime(frontendDir) {
  const declared = readPackageJson(frontendDir, '..').engines?.node
  if (!declared) throw new Error('locale-catalog: frontend/package.json declares no node engine')
  if (!/^\d+\.\d+\.\d+$/.test(declared)) {
    throw new Error(
      `locale-catalog: frontend/package.json must pin an exact node version, not ${declared}`,
    )
  }
  if (declared !== process.versions.node) {
    throw new Error(
      `locale-catalog: this generator is pinned to Node ${declared} (frontend/package.json ` +
        `engines) but is running on ${process.versions.node}. Run it through mise ` +
        `(\`mise x -- node ...\`) or align mise.toml, the Dockerfile, CI and the offline build.`,
    )
  }
  return { version: declared }
}

export function toolchainVersions(frontendDir) {
  const compiler = readPackageJson(frontendDir, '@intlify/message-compiler').version
  const required = readPackageJson(frontendDir, '@intlify/core-base').dependencies?.[
    '@intlify/message-compiler'
  ]
  if (required !== compiler) {
    throw new Error(
      `locale-catalog: @intlify/message-compiler ${compiler} is installed, but vue-i18n's ` +
        `@intlify/core-base requires ${required}`,
    )
  }
  for (const nested of ['vue-i18n', '@intlify/core-base']) {
    const duplicate = join(
      frontendDir,
      'node_modules',
      ...nested.split('/'),
      'node_modules',
      '@intlify',
      'message-compiler',
    )
    if (existsSync(duplicate)) {
      throw new Error(`locale-catalog: a second @intlify/message-compiler is installed under ${nested}`)
    }
  }

  return {
    '@intlify/core-base': readPackageJson(frontendDir, '@intlify/core-base').version,
    '@intlify/message-compiler': compiler,
    'jsonc-parser': readPackageJson(frontendDir, 'jsonc-parser').version,
    parse5: readPackageJson(frontendDir, 'parse5').version,
    vite: readPackageJson(frontendDir, 'vite').version,
    'vue-i18n': readPackageJson(frontendDir, 'vue-i18n').version,
    node: nodeRuntime(frontendDir).version,
  }
}

// Tags every string leaf of a locale JSON module with the file it came from,
// so composition ownership can be read off the *evaluated* tree instead of
// being guessed at. Boxed strings survive spreads and shallow merges by
// reference, so the last writer of any key is exactly the file whose tag the
// composed tree carries.
const OWNER_TAG = '__localeCatalogOwner'

function ownershipTagger(root) {
  return {
    name: 'locale-catalog-ownership',
    // `post`, so this rewrites the module Vite's own JSON plugin produced
    // rather than competing with it.
    enforce: 'post',
    transform(code, id) {
      const [path] = id.split('?')
      if (!path.endsWith('.json') || !path.startsWith(root)) return null

      // Vite's JSON plugin may emit named exports alongside the default, so
      // the original module is kept intact and only its default is wrapped.
      const marker = 'export default '
      const start = code.lastIndexOf(marker)
      if (start === -1) {
        // Fail closed: ownership analysis must never silently skip a file.
        throw new Error(`locale-catalog: unexpected JSON module shape for ${path}`)
      }
      const owner = toPosix(relative_(root, path))
      const head = code.slice(0, start)
      const value = code.slice(start + marker.length)
      return `${head}
        const __owner = ${JSON.stringify(owner)}
        const __tag = (value) => {
          if (typeof value === 'string') {
            const boxed = new String(value)
            boxed[${JSON.stringify(OWNER_TAG)}] = __owner
            return boxed
          }
          if (Array.isArray(value)) return value.map(__tag)
          if (value !== null && typeof value === 'object') {
            const out = {}
            for (const key of Object.keys(value)) out[key] = __tag(value[key])
            return out
          }
          return value
        }
        const __rawDefault = ${value}
        export default __tag(__rawDefault)
      `
    },
  }
}

function entryModule() {
  return `
    export { uiLocales, uiLocaleFor, preferredLanguage } from '@/locales/language'
    export { supportedLocales, loadLocaleMessages } from '@/locales/messages'
    export { formatContent, replaceIcons } from '@/arkham/helpers'

    // Every locale source file on its own, so composition can be checked for
    // silently overridden contributors (see inventory.mjs).
    const localeFiles = import.meta.glob('@/locales/**/*.json', { eager: true })
    const homebrewFiles = import.meta.glob('@homebrew/*/locales/**/*.json', { eager: true })
    export const fileTrees = Object.entries({ ...localeFiles, ...homebrewFiles }).map(
      ([path, module]) => ({ path, tree: module.default }),
    )
  `
}

/**
 * Bundles and evaluates the production locale modules.
 *
 * Returns the composed message tree per supported locale plus the production
 * `formatContent`/`replaceIcons`/locale-resolution functions, so the generator
 * derives icon and fallback semantics from shipped code instead of copying
 * lists into this toolchain.
 */
/**
 * Composes the locale trees a second time with every JSON leaf tagged by its
 * source file, so `inventory.mjs` can attribute each published string to the
 * contributor that actually won it.
 */
export async function loadOwnershipTrees(frontendDir) {
  const { build } = await import('vite')
  const outDir = join(frontendDir, 'node_modules', '.locale-catalog', `${process.pid}-${buildSerial++}`)
  rmSync(outDir, { recursive: true, force: true })
  try {
    const bundle = await bundleLocaleSources(build, frontendDir, outDir, [
      ownershipTagger(resolve(frontendDir)),
    ])
    const trees = {}
    for (const locale of bundle.supportedLocales) {
      trees[locale] = (await bundle.loadLocaleMessages(locale)).messages
    }
    return { trees, ownerKey: OWNER_TAG }
  } finally {
    rmSync(outDir, { recursive: true, force: true })
  }
}

export async function loadLocaleSources(frontendDir) {
  const { build } = await import('vite')
  // A fresh directory per call: Node caches ES modules by URL, so reusing one
  // path would silently re-evaluate the first bundle on every later build in
  // the same process — and a repeated-build determinism check would then
  // compare a bundle against itself.
  const outDir = join(frontendDir, 'node_modules', '.locale-catalog', `${process.pid}-${buildSerial++}`)
  rmSync(outDir, { recursive: true, force: true })

  try {
    return await bundleLocaleSources(build, frontendDir, outDir)
  } finally {
    rmSync(outDir, { recursive: true, force: true })
  }
}

let buildSerial = 0

async function bundleLocaleSources(build, frontendDir, outDir, extraPlugins = []) {
  await build({
    // Pinned so the build never depends on the working directory the
    // generator happens to be invoked from.
    root: frontendDir,
    configFile: false,
    logLevel: process.env.LOCALE_CATALOG_DEBUG ? 'info' : 'error',
    resolve: {
      alias: {
        '@': resolve(frontendDir, 'src'),
        '@homebrew': resolve(frontendDir, 'homebrew'),
      },
    },
    plugins: [
      ...extraPlugins,
      {
        name: 'locale-catalog-entry',
        resolveId: (id) => (id === 'locale-catalog-entry' ? VIRTUAL_ENTRY : null),
        load: (id) => (id === VIRTUAL_ENTRY ? entryModule() : null),
      },
    ],
    build: {
      ssr: true,
      minify: false,
      outDir,
      emptyOutDir: true,
      write: true,
      rollupOptions: {
        input: { entry: 'locale-catalog-entry' },
        output: { format: 'es', entryFileNames: '[name].mjs', chunkFileNames: '[name].mjs' },
      },
    },
  })

  const bundle = await import(pathToFileURL(join(outDir, 'entry.mjs')).href)
  if (extraPlugins.length > 0) return bundle

  const locales = [...bundle.supportedLocales]
  const messages = {}
  for (const locale of locales) {
    const loaded = await bundle.loadLocaleMessages(locale)
    if (loaded.locale !== locale) {
      throw new Error(`locale-catalog: ${locale} resolved to ${loaded.locale}`)
    }
    messages[locale] = loaded.messages
  }

  return {
    locales,
    messages,
    fileTrees: bundle.fileTrees,
    uiLocales: [...bundle.uiLocales],
    uiLocaleFor: bundle.uiLocaleFor,
    preferredLanguage: bundle.preferredLanguage,
    formatContent: bundle.formatContent,
    replaceIcons: bundle.replaceIcons,
  }
}

/**
 * Classifies a message placeholder by asking the production formatter what it
 * would do with `{name}`, so the icon and literal-escape vocabularies are
 * whatever `src/arkham/helpers.ts` currently defines — including homebrew
 * icons discovered from each `homebrew/<campaign>/icons.json` — and can never
 * drift from it.
 */
export function makeVariableClassifier({ formatContent, replaceIcons }, assetPathVariables) {
  const cache = new Map()
  return (name) => {
    const cached = cache.get(name)
    if (cached) return cached

    let classification
    const token = `{${name}}`
    if (Object.hasOwn(assetPathVariables, name)) {
      classification = { role: 'assetPath', base: assetPathVariables[name] }
    } else if (replaceIcons(token) !== token) {
      classification = { role: 'icon' }
    } else if (/[*_]/.test(name)) {
      // `formatContent`'s emphasis pass would pair against the probe token
      // itself, so it cannot answer the literal-escape question for this name.
      classification = { role: 'text' }
    } else {
      const formatted = formatContent(token)
      if (formatted === token) {
        classification = { role: 'text' }
      } else if (/[<>]/.test(formatted)) {
        throw new Error(
          `locale-catalog: production formatContent() turned {${name}} into markup (${formatted}); ` +
            'the catalog cannot classify it safely',
        )
      } else {
        classification = { role: 'literal', text: formatted }
      }
    }

    cache.set(name, classification)
    return classification
  }
}
